### ISSUE TITLE
Error due to CUDA settings

### ISSUE THREAD

**Issue by saioruganti** [SystemsGenetics/KINC#115]
I am using `KINC:cscm-work` branch and `ACE:develop` branch

I got the following error when I tried to run kinc on local machine and tried to import the expression matrix:
`Unknown exception caught!\n`

Then I realized the issue was due to missing NVIDIA drivers. So I installed the drivers and the issue was resolved while importing the expression matrix.

But the same error occurred when I tried to run the similarity analytic.  
The error doesn't occur once I change kinc settings `kinc settings set cuda none`

I am not sure of what might be the issue or how to resolve it.

**Comment by spficklin** [comment]
@saioruganti I think we need a bit more information on what you did to set up your machine to run KINC.  I'm not able to reproduce this problem.  I think the fix in ACE that @4ctrl-alt-del applied to automatically disable CUDA will help in this case.

**Comment by bentsherman** [comment]
@saioruganti Unfortunately because KINC is built with the CUDA Driver APi, weird things can happen if you don't have the NVIDIA drivers installed, regardless of whether you have a GPU or not.

The above solution is fine, you can just disable CUDA. Another solution is here:

https://github.com/SystemsGenetics/KINC/blob/master/docker/Dockerfile#L21

You can install the NVIDIA "headless driver" which provides just the header files. We use this for our KINC CPU containers and it works perfectly.

**Comment by bentsherman** [comment]
I will add this to the troubleshooting docs for future reference.
