### ISSUE TITLE
Visualization Tool Transivity

### ISSUE THREAD

**Issue by JohnHadish** [SystemsGenetics/KINC#156]
The `kinc-3D-viewer.py` fails if the graph given to it is not "simple". This means that it will fail for most graphs produced by GMMs that have more than one condition, as there is the possibility for there to be two edges between the same node pair.

Error message:
```
Reading network file...
Reading GEM file...
Reading experioment annotation file...
Traceback (most recent call last):
  File "../kinc-3d-viewer.py", line 1266, in <module>
    main()
  File "../kinc-3d-viewer.py", line 1242, in main
    glayout = calculate_2d_layout(net, net_prefix, args.redo_layout, args.iterations)
  File "../kinc-3d-viewer.py", line 202, in calculate_2d_layout
    t = pd.Series(g.transitivity_local_undirected(), index=g.vs['name'])
igraph._igraph.InternalError: Error at /project/vendor/source/igraph/src/triangles.c:492: Transitivity works on simple graphs only, Invalid value
```

**Comment by spficklin** [comment]
Oddly, I can't reproduce this.  See screenshot below.  I suspect the problem is a different version of the python igraph library.. I tested with version 0.7.1.post6-5.  What version are you using?

![image](https://user-images.githubusercontent.com/1719352/85911588-e9b61800-b7da-11ea-8333-d93bf80ee8c7.png)

**Comment by JohnHadish** [comment]
Fixed by pull request 167
