### ISSUE TITLE
KINC 3D viewer mangles TTY

### ISSUE THREAD

**Issue by JohnHadish** [SystemsGenetics/KINC#159]
When I exit the KINC 3D viewer, my cursor dissapears from my terminal. This is a minor thing, but is rather annoying when I am trying to look at multiple networks and I just want to be able to change the `--net` parameter in my `kinc-3d-viewer.py` command. Since I can not see my blinking cursor, I can not tell what parameter I am going to modify.

Here is a link I found that describes the problem better than I can:
https://unix.stackexchange.com/questions/6890/what-is-making-my-cursor-randomly-disappear-when-using-gnome-teminal

I am not sure if this is an issue with KINC 3D or Dash.

**Comment by spficklin** [comment]
Yeah, I see that this happens.  However, running `reset` on the command-line brings back the cursor.  I'm guessing this is a dash or progress bar problem and I don't know how to  immediately fix it.  As this isn't an urgent thing, I'm going to mark this as "fiture fix" but close it out because I don't think we have time to really dig into it.
