### ISSUE TITLE
Loop unrolling for pair-wise GMMs

### ISSUE THREAD

**Issue by bentsherman** [SystemsGenetics/KINC#16]
Since we are only using GMMs with D=2, I think we can get a great amount of speedup with loop unrolling. GMMs of this problem size perform many of the following operations:
- adding 2x1 vectors
- scaling 2x1 and 2x2 matrices
- computing products of 2x1 and 2x2 matrices
- computing determinants and inverses of 2x2 matrices

These operations are typically done with BLAS / LAPACK routines which use loops, but because these matrices are so small, the loop overhead is significant. I wrote a quick program that runs a few tests with addition and multiplication and I'm able to get roughly 2x speedup. I think this is definitely worth doing in in GPU implementation because the GSL routines won't be available there, but I may go ahead and do it for the serial implementation too.

**Comment by feltus** [comment]
That is way cool!


Sent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: Ben Shealy <notifications@github.com> Date: 1/3/18  2:08 PM  (GMT-05:00) To: SystemsGenetics/KINC <KINC@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Subject: [SystemsGenetics/KINC] Loop unrolling for pair-wise GMMs (#16) 
Since we are only using GMMs with D=2, I think we can get a great amount of speedup with loop unrolling. GMMs of this problem size perform many of the following operations:

adding 2x1 vectors
scaling 2x1 and 2x2 matrices
computing products of 2x1 and 2x2 matrices
computing determinants and inverses of 2x2 matrices

These operations are typically done with BLAS / LAPACK routines which use loops, but because these matrices are so small, the loop overhead is significant. I wrote a quick program that runs a few tests with addition and multiplication and I'm able to get roughly 2x speedup. I think this is definitely worth doing in in GPU implementation because the GSL routines won't be available there, but I may go ahead and do it for the serial implementation too.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/SystemsGenetics/KINC","title":"SystemsGenetics/KINC","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/SystemsGenetics/KINC"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"Loop unrolling for pair-wise GMMs (#16)"}],"action":{"name":"View Issue","url":"https://github.com/SystemsGenetics/KINC/issues/16"}}}

**Comment by spficklin** [comment]
Sounds like a great idea.   @mtmcgowan has been looking at our use of GMMs.  In the end we may not need to do GMM for every pair-wise comparison.  In some cases we may be able to perform less expensive tests to determine if GMM is needed.    That will probably give some speedup as well.

**Comment by feltus** [comment]
Excellent idea


Sent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: Stephen Ficklin <notifications@github.com> Date: 1/5/18  4:15 PM  (GMT-05:00) To: SystemsGenetics/KINC <KINC@noreply.github.com> Cc: Alex Feltus <alex.feltus@gmail.com>, Comment <comment@noreply.github.com> Subject: Re: [SystemsGenetics/KINC] Loop unrolling for pair-wise GMMs (#16) 
Sounds like a great idea.   @mtmcgowan has been looking at our use of GMMs.  In the end we may not need to do GMM for every pair-wise comparison.  In same cases we may be able to perform less expensive tests to determine if GMM is needed.    That will probably give some speedup as well.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/SystemsGenetics/KINC","title":"SystemsGenetics/KINC","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/SystemsGenetics/KINC"}},"updates":{"snippets":[{"icon":"PERSON","message":"@spficklin in #16: Sounds like a great idea.   @mtmcgowan has been looking at our use of GMMs.  In the end we may not need to do GMM for every pair-wise comparison.  In same cases we may be able to perform less expensive tests to determine if GMM is needed.    That will probably give some speedup as well.  "}],"action":{"name":"View Issue","url":"https://github.com/SystemsGenetics/KINC/issues/16#issuecomment-355667368"}}}

**Comment by bentsherman** [comment]
K-means and GMM are now both implemented in serial and OpenCL with loop unrolling.

**Comment by spficklin** [comment]
Awesome! @bentsherman
