### ISSUE TITLE
Add documentation 

### ISSUE THREAD

**Issue by wpoehlm** [SystemsGenetics/KINC#26]
There is a lack of documentation for how to run the three steps (similarity, threshold, extract).  At the very least, example command lines should be provided for the version1 branch (I can work on this).

**Comment by bentsherman** [comment]
Merging with your other issue since they can be dealt with simultaneously.

**Comment by feltus** [comment]
1 trillion Karma points.


Sent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: Ben Shealy <notifications@github.com> Date: 2/13/18  7:37 PM  (GMT-05:00) To: SystemsGenetics/KINC <KINC@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Subject: Re: [SystemsGenetics/KINC] Add documentation (#26) 
Merging with your other issue since they can be dealt with simultaneously.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/SystemsGenetics/KINC","title":"SystemsGenetics/KINC","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/SystemsGenetics/KINC"}},"updates":{"snippets":[{"icon":"PERSON","message":"@bentsherman in #26: Merging with your other issue since they can be dealt with simultaneously."}],"action":{"name":"View Issue","url":"https://github.com/SystemsGenetics/KINC/issues/26#issuecomment-365455002"}}}
