### ISSUE TITLE
Waiting for multiple OpenCL events in parallel

### ISSUE THREAD

**Issue by bentsherman** [SystemsGenetics/KINC#27]
I wanted to point out that there are now a few places where multiple OpenCL events are generated and ostensibly should happen in parallel but right now the implementation is not completely correct. In particular `runExecuteBlock` in KMeans / GMM and `runStartBlock` in Spearman / Pearson. In all four cases, two buffers are copied in parallel, so `block.event` only has the event for the second copy at the end of the function. Since the last event happens to be for the larger buffer in every case, practically speaking it probably isn't a problem, but it's still a race condition I'd rather not have.

@4ctrl-alt-del what do you think the best way would be to handle parallel events like this? Now that I'm writing about it, I could replace `block.event` with `block.events` and write a method in `Block` that checks if all events are done... but still I'd like to get your thoughts on this issue, make sure I'm understanding it correctly.

**Comment by 4ctrl-alt-del** [comment]
Commands given to the command queue of the OpenCL device is in unordered mode which means order of operations is NOT promised in anyway. Even assuming one will finish last because it takes a lot longer is false. For hardware reasons or who knows what the OpenCL drivers could decide to do the larger one first and the small one last in serial. There is no race condition calling operations on the command queue is thread safe along with OpenCL events. You are correct though you must check for ALL operations are done if they have to be before you can continue. So yes, your idea is what I would do make a list of all events and wait until all of them finish.
