### ISSUE TITLE
Suggested changes to similarity analytic

### ISSUE THREAD

**Issue by spficklin** [SystemsGenetics/KINC#42]
Can we make these changes to the similarity analytic
1)  Have the ability to turn off clustering all-together?  We have 'gmm' and ''kmeans'. Can we have a 'none'?  
2) Change the default "Criterion" from BIC to ICL.  I think that for KINC v1 the default was BIC but after discussions with MixMod folks and running my own ICL does seem to be a better default as it does a better job of finding fewer clusters.
3)  Can we put the Block Size and kernel Size in a "GPU settings" section?  Does QT support collapsible field sets.  That would be nice to hide those away by default but let the user tweak them if needed.
4)  I think the pre and post outlier removal should be checked by default?  Any objections?

**Comment by 4ctrl-alt-del** [comment]
For 3. that will go away in the new version of ACE (ACE dynamically and automatically handles those settings).

**Comment by bentsherman** [comment]
I can implement 1 and 2 pretty quickly. I'm not quite ready to have outlier removal selected by default because they haven't been tested very much. Once you can generate a Yeast network I think you should run a separate test where you enable both (or perhaps enable one at a time) to see how they affect results.

**Comment by bentsherman** [comment]
1 and 2 have been implemented, 3 will be covered by next version of ACE, and 4 will be done after outlier removal is tested more thoroughly. Closing this issue.
