### ISSUE TITLE
Cannot compile KINC v3.2.2 on Kamiak

### ISSUE THREAD

**Issue by 4ctrl-alt-del** [SystemsGenetics/KINC#66]
So I have been trying to compile unsuccessfully KINC since yesterday and I have been having a heck of a time getting its lapacke dependency to work. After loading an openblas module it was able to precompile the object files but then at the end it wasn't able link complaining it could not find the library -llapacke. This is the most confusing library dependency I have ever dealt with, help?

How can the openblas module satisfy finding the header files for lapacke yet not supply the actual library lapacke? BTW this is apparently common because the same thing happens on my local machine when I install openblas... apparently it is a fake library or something?

**Comment by bentsherman** [comment]
openblas in particular is a tricky library because it's implementing the "standard" BLAS and LAPACK interfaces. There are a couple linker flags that are potentially involved here:
- `-lblas`, `-lcblas`: BLAS (Fortran interface) and it's C wrapper
- `-llapack`, `-llapacke`: LAPACK (Fortran interface) and it's C wrapper
- `-lopenblas`: All of openblas

Some combination of these flags should work, but in my experience it's different for every system. You can try `-lopenblas` by itself, or you can try the other four together. In the latter case, order matters and you may not need all four.

Can you provide your build log? If I can see the linker errors then I might be able to tell which flags you should use.

**Comment by bentsherman** [comment]
Things are also complicated by the fact that GSL needs a CBLAS library, and it's possible to provide an implementation other than the GSL default. I'm not entirely sure how that's interacting with LAPACKE but it hasn't caused any problems for me. In fact I think that on my end LAPACKE is using the GSL BLAS implementation.

**Comment by 4ctrl-alt-del** [comment]
````
$ make
cd core/ && ( test -e Makefile || /data/ficklin/software/qt-5.10.1/5.10.1/gcc_64/bin/qmake -o Makefile /home/josh.burns/projects/KINC/src/core/core.pro PREFIX=/home/josh.burns/software MPICXX=no ) && make -f Makefile 
make[1]: Entering directory `/home/josh.burns/projects/KINC/build/core'
make[1]: Nothing to be done for `first'.
make[1]: Leaving directory `/home/josh.burns/projects/KINC/build/core'
cd cli/ && ( test -e Makefile || /data/ficklin/software/qt-5.10.1/5.10.1/gcc_64/bin/qmake -o Makefile /home/josh.burns/projects/KINC/src/cli/cli.pro PREFIX=/home/josh.burns/software MPICXX=no ) && make -f Makefile 
make[1]: Entering directory `/home/josh.burns/projects/KINC/build/cli'
g++ -Wl,-O1 -Wl,-rpath,/data/ficklin/software/qt-5.10.1/5.10.1/gcc_64/lib -o kinc main.o qrc_opencl.o   -L/home/josh.burns/projects/KINC/src/../build/libs -lkinccore -lacecore -lgsl -lgslcblas -llapack -llapacke -lOpenCL -lmpi -laceconsole -L/data/ficklin/software/qt-5.10.1/5.10.1/gcc_64/lib -lQt5Gui -lQt5Core -lGL -lpthread 
/usr/bin/ld: cannot find -llapack
/usr/bin/ld: cannot find -llapacke
collect2: error: ld returned 1 exit status
make[1]: *** [kinc] Error 1
make[1]: Leaving directory `/home/josh.burns/projects/KINC/build/cli'
make: *** [sub-cli-make_first] Error 2
$
$ module list

Currently Loaded Modules:
  1) workspace_maker/master   4) MPI/openmpi/3.0.0   7) openblas/0.3.0
  2) StdEnv                   5) cuda/9.1.85
  3) gcc/6.1.0                6) qt/5.10.1

 

$
````

**Comment by bentsherman** [comment]
So then the question is where the shared libraries for lapack and lapacke are, and how your openblas module is providing them. The shared libraries should be in some central folder like `/software/openblas/...`, whereverr the software for each module is stored. You'll also need to consult the modulefile for openblas -- normally the modulefile will edit environment variables like `$PATH` and `$LD_LIBRARY_PATH` to include the appropriate paths from the module's software folder. You need to see if this module is actually doing that, and if it isn't, you'll have to add those paths manually or have the sysadmin correct the modulefile (because it should be providing that). I believe you need to update `$LIBRARY_PATH` for linking, and then `$LD_LIBRARY_PATH` for when you run the executable. I show something similar in the KINC Ubuntu setup docs.

If you want to just print the openblas modulefile that should be fine. And the directory tree for the openblas software folder.

**Comment by 4ctrl-alt-del** [comment]
So it looks like $LIBRARY_PATH was set correctly, but it appears openblas does not provide lapack or lapacke?

````
$ echo $LIBRARY_PATH
/opt/apps/openblas/0.3.0/lib:/opt/apps/cuda/9.1.85/gcc/6.1.0/lib64:/opt/apps/openmpi/3.0.0/gcc/6.1.0/lib:/home/josh.burns/software/lib
$ ls /opt/apps/openblas/0.3.0/lib
cmake                                   libopenblas.so
libopenblas.a                           libopenblas.so.0
libopenblas_sandybridgep-r0.3.0.dev.a   pkgconfig
libopenblas_sandybridgep-r0.3.0.dev.so
$
````

**Comment by bentsherman** [comment]
Well they may not be providing the lapack libraries explicitly, it depends on how they set up this module. But `libopenblas.so` should contain all of the BLAS and LAPACK code so you could try just using the `-lopenblas` flag.

**Comment by 4ctrl-alt-del** [comment]
So I edited KINC.pri and replaced "-llapack -llapacke" with "-lopenblas", and now I get this build log error:

````
$ make qmake_all
cd core/ && /data/ficklin/software/qt-5.10.1/5.10.1/gcc_64/bin/qmake -o Makefile /home/josh.burns/projects/KINC/src/core/core.pro PREFIX=/home/josh.burns/software MPICXX=no
cd core/ && make -f Makefile qmake_all
make[1]: Entering directory `/home/josh.burns/projects/KINC/build/core'
make[1]: Nothing to be done for `qmake_all'.
make[1]: Leaving directory `/home/josh.burns/projects/KINC/build/core'
cd cli/ && /data/ficklin/software/qt-5.10.1/5.10.1/gcc_64/bin/qmake -o Makefile /home/josh.burns/projects/KINC/src/cli/cli.pro PREFIX=/home/josh.burns/software MPICXX=no
cd cli/ && make -f Makefile qmake_all
make[1]: Entering directory `/home/josh.burns/projects/KINC/build/cli'
make[1]: Nothing to be done for `qmake_all'.
make[1]: Leaving directory `/home/josh.burns/projects/KINC/build/cli'
cd tests/ && /data/ficklin/software/qt-5.10.1/5.10.1/gcc_64/bin/qmake -o Makefile /home/josh.burns/projects/KINC/src/tests/tests.pro PREFIX=/home/josh.burns/software MPICXX=no
cd tests/ && make -f Makefile qmake_all
make[1]: Entering directory `/home/josh.burns/projects/KINC/build/tests'
make[1]: Nothing to be done for `qmake_all'.
make[1]: Leaving directory `/home/josh.burns/projects/KINC/build/tests'
cd gui/ && /data/ficklin/software/qt-5.10.1/5.10.1/gcc_64/bin/qmake -o Makefile /home/josh.burns/projects/KINC/src/gui/gui.pro PREFIX=/home/josh.burns/software MPICXX=no
cd gui/ && make -f Makefile qmake_all
make[1]: Entering directory `/home/josh.burns/projects/KINC/build/gui'
make[1]: Nothing to be done for `qmake_all'.
make[1]: Leaving directory `/home/josh.burns/projects/KINC/build/gui'
$
$ make clean
...
...
$
$ make
...
...
cd core/ && ( test -e Makefile || /data/ficklin/software/qt-5.10.1/5.10.1/gcc_64/bin/qmake -o Makefile /home/josh.burns/projects/KINC/src/core/core.pro PREFIX=/home/josh.burns/software MPICXX=no ) && make -f Makefile 
make[1]: Entering directory `/home/josh.burns/projects/KINC/build/core'
make[1]: Nothing to be done for `first'.
make[1]: Leaving directory `/home/josh.burns/projects/KINC/build/core'
cd cli/ && ( test -e Makefile || /data/ficklin/software/qt-5.10.1/5.10.1/gcc_64/bin/qmake -o Makefile /home/josh.burns/projects/KINC/src/cli/cli.pro PREFIX=/home/josh.burns/software MPICXX=no ) && make -f Makefile 
make[1]: Entering directory `/home/josh.burns/projects/KINC/build/cli'
g++ -Wl,-O1 -Wl,-rpath,/data/ficklin/software/qt-5.10.1/5.10.1/gcc_64/lib -o kinc main.o qrc_opencl.o   -L/home/josh.burns/projects/KINC/src/../build/libs -lkinccore -lacecore -lgsl -lgslcblas -lopenblas -lOpenCL -lmpi -laceconsole -L/data/ficklin/software/qt-5.10.1/5.10.1/gcc_64/lib -lQt5Gui -lQt5Core -lGL -lpthread 
/usr/bin/ld: warning: libgfortran.so.4, needed by /opt/apps/openblas/0.3.0/lib/libopenblas.so, not found (try using -rpath or -rpath-link)
/opt/apps/openblas/0.3.0/lib/libopenblas.so: undefined reference to `_gfortran_concat_string@GFORTRAN_7'
/opt/apps/openblas/0.3.0/lib/libopenblas.so: undefined reference to `_gfortran_etime@GFORTRAN_7'
collect2: error: ld returned 1 exit status
make[1]: *** [kinc] Error 1
make[1]: Leaving directory `/home/josh.burns/projects/KINC/build/cli'
make: *** [sub-cli-make_first] Error 2
$
````

**Comment by bentsherman** [comment]
Hmm, it looks like your openblas module was built with gcc 7 / gfortran 7. Perhaps if you swap out gcc 6.1.0 for gcc 7 it will work.

On a related note, I thought that Lmod prevented this kind of issue by tying every module to a specific compiler version. So that if you tried to load openblas it would force you to switch to the gcc 7 module or throw an error...

**Comment by 4ctrl-alt-del** [comment]
Changing to gcc 7 worked like a charm. While I understand how much more efficient adding this additional library dependency provides to RMT in KINC, I am somewhat concerned how very convoluted and confusing the needed library is. It still doesn't work on my home machine but for our testing that is not currently very important.

**Comment by bentsherman** [comment]
Yeah sorry about the trouble, it definitely shouldn't be that complicated. But on HPC systems it tends to be. It took me a good year or two to develop a solid understanding of how to properly set up software on a cluster. There are a lot of ways to do it wrong and even small mistakes can create big headaches down the road. Case in point:

- the openblas module should have also provided the lapack / lapacke libraries, because developers expect to be able to swap out different implementations without having to change linker flags
- the openblas module also should have been linked to gcc 7 so that you wouldn't be able to load the module without gcc 7

HPC environments just aren't as mature as the standard Linux distros... you have to learn to do these kinds of things yourself. The good thing at least is that end users of KINC probably won't have to deal with these details, because either KINC will already be available as a module or as a container.

**Comment by 4ctrl-alt-del** [comment]
Well apparently I jumped the gun on closing this issue. I was going to start my first test this morning and this happened:

````
(normal)$ idev ...
...
...
(idev)$ time kinc run similarity --input Yeast.emx --ccm yeast.ccm --cmx yeast.cmx --clusmethod gmm --corrmethod spearman --minexpr -inf --minsamp 30 --minclus 1 --maxclus 5 --crit ICL --preout TRUE --postout TRUE --mincorr 0.5 --maxcorr 1 --gsize 4096 --lsize 32
kinc: error while loading shared libraries: libgfortran.so.4: cannot open shared object file: No such file or directory

real    0m0.436s
user    0m0.001s
sys     0m0.008s
(idev)$ kinc
kinc: error while loading shared libraries: libgfortran.so.4: cannot open shared object file: No such file or directory
(idev)$ exit
exit
...
(normal)$ kinc
../../src/console/eapplication.cpp:146
int EApplication::exec()
NO ARGUMENTS
No arguments given, exiting...
(normal)$
````

Apparently there is a library that cannot be linked at runtime ONLY in the idev environment, but it works fine in my normal account. This BLAS library you added into KINC is turning into a nightmare for me. I haven't even been able to start running any test at all after a week of dealing with this.

If I am having this much frustration with this BLAS library and I am a developer who literally made ACE and the new KINC, I am concerned about normal users. Frankly if this was a neat program I heard of and tried to use it I would have given up and deleted it sometime last week because of this BLAS headache...

**Comment by 4ctrl-alt-del** [comment]
Is there an alternative to an openblas I can use to fulfill these dependencies?

**Comment by bentsherman** [comment]
Is `idev` the way that you access compute nodes interactively? You need to make sure that you have the proper environment variables defined, in particular you'll need `PATH` and `LD_LIBRARY_PATH` to include the proper directories in order to run KINC. That gfortran library probably belongs to the `gcc` module that you used. As before, you need to examine the module files for yourself -- where is this shared library located? And is the `gcc` module providing it through `LD_LIBRARY_PATH`? If not you'll need to update your environment manually.

**Comment by 4ctrl-alt-del** [comment]
Figured it out, apparently idev changes your loaded modules on the fly without letting you know. I had to unload and reload gcc 7. The strange this is it says it is loaded before I do that. I will close this comment after I finish my first test just to be sure... BLAS has made me very paranoid about it working...

**Comment by spficklin** [comment]
@4ctrl-alt-del can you add compile instructions to our GitLab page so we have a record of what you needed to do?

**Comment by 4ctrl-alt-del** [comment]
@spficklin  sure
