### ISSUE TITLE
correlation matrix goes out of range

### ISSUE THREAD

**Issue by 4ctrl-alt-del** [SystemsGenetics/KINC#8]
Something wrong with the diagonal size of cmatrix along with going way beyond the limit of comparisons... investigate.

**Comment by feltus** [comment]
Don't we have the coolest job ever?  Alex o.j.


Sent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: Josh B <notifications@github.com> Date: 5/5/17  1:33 PM  (GMT-05:00) To: SystemsGenetics/KINC <KINC@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Subject: [SystemsGenetics/KINC] correlation matrix goes out of range (#8) 
Something wrong with the diagonal size of cmatrix along with going way beyond the limit of comparisons... investigate.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/SystemsGenetics/KINC","title":"SystemsGenetics/KINC","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/SystemsGenetics/KINC"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"correlation matrix goes out of range (#8)"}],"action":{"name":"View Issue","url":"https://github.com/SystemsGenetics/KINC/issues/8"}}}

**Comment by 4ctrl-alt-del** [comment]
Found bug;
It wasn't that the correlation matrix was going too far, it was another problem all together.
A static function CMatrix::diag_size() is used to get the total size of a diagonal matrix, it was greatly under the required value so when the correlations got far enough the file wasn't big enough

Have not yet tested to see if this fixes the original problem.

**Comment by 4ctrl-alt-del** [comment]
confirmed issue resolved, fixed in commit 26f18cd4eed1407d91098a3c365cd4494c5b7493
