### ISSUE TITLE
Scaling RMT to large GEMs

### ISSUE THREAD

**Issue by bentsherman** [SystemsGenetics/KINC#83]
I am currently trying to threshold the panGTEX GEM, which has over 50,000 genes and 10,000 samples. Here is the latest thresholding result:
```
threshold:    0.753
prune matrix: 52493
eigenvalues: 52493
unique eigenvalues: 52492
chi-squared: 20924.5
```

So the chi-squared value is __really__ large, and I don't expect it to decrease anytime soon, much less to go below the critical threshold of 99.607. We've encountered this issue with other GEMs as well, although so far we've always found a way around it somehow.

I think the number of genes is the biggest reason for this problem, because it influences the number of eigenvalues, which in turn affects the magnitude of the chi-squared value:
```
   // compute chi-squared value from the histogram
   float chi {0.0};

   for ( int i = 0; i < (int) histogram.size(); ++i )
   {
      // compute O_i, the number of elements in bin i
      float O_i {histogram[i]};

      // compute E_i, the expected value of Poisson distribution for bin i
      float E_i {(expf(-i * histogramBinWidth) - expf(-(i + 1) * histogramBinWidth)) * values.size()};

      // update chi-squared value based on difference between O_i and E_i
      chi += (O_i - E_i) * (O_i - E_i) / E_i;
   }
```

Another interesting observation is that, in the case of panGTEX, all of the eigenvalues are considered unique, where "unique" means that the eigenvalue is at least 10^-6 greater than the previous eigenvalue in order. So I'm wondering if this threshold of 10^-6 is not appropriate for matrices of this size? I would like to experiment with this parameter.

@spficklin Do you have any advice for using RMT properly on matrices of this size?

**Comment by spficklin** [comment]
Hi @bentsherman.  I wouldn't say the problem is with the size of the matrix, the large matrix size is more of a symptom of something else gone wrong.  At a correlation value of 0.753 and a matrix size of 52K it means your data is very highly correlated!  It is not typical that you would have a matrix of that size with a threshold of 0.75.  So, something is going on that is leading to too much correlation.  It's hard to say what that might be exactly without digging down into the data.  What does the distribution of your sample density plots look like?

**Comment by bentsherman** [comment]
Well I think with a large prune matrix there could still be relatively few correlations that just happen to cover most of the genes. The matrix still has to be very large, but it might also be extremely sparse. So there are a bunch of visualizations that I need to make a note of:

- distribution of correlations
- coverage of pruned correlations (e.g. 0.99) across genes
- distribution of eigenvalues and eigenvalue spacings
- pairwise scatter / density plots for pruned correlations (e.g. 0.99)

We have some Python scripts in the KINC repo already for some of these visualizations, I'll see if I can expand `visualize.py` later on. I'll take a look at the density plots when I get a chance.

**Comment by spficklin** [comment]
> I think with a large prune matrix there could still be relatively few correlations that just happen to cover most of the genes

Perhaps... but it's not something I've typically seen.  In the past when I've seen this much correlation it occurs with too few samples, or with some sort of non-biological noise in the data. I'm sure there are other causes too.  We had this problem with the cancer data and had to remove all the perfect correlation.   I don't think this is more likely as the number of samples increases, I would expect the opposite (less correlation). 

Some of those visualizations would be really handy in KINC rather than in a python script if that's easy enough to do.  It would be really nice to be able to look at correlation distributions right in KINC and have those plots stored as metadata in the files.....

**Comment by bentsherman** [comment]
I've added a visualization for RMT in `kinc-threshold.py`, which shows the sorted unique eigenvalues and the nearest-neighbor spacing distribution for each threshold as the algorithm proceeds. My concerns are mostly with some of the constants involved in RMT:

- the epsilon for determining unique eigenvalues (1e-6)
- the range of the NNSD (0 to 3)
- the number of bins, aka degrees of freedom (60)

From thresholding the Yeast network (no GMMs), I saw that (1) many unique eigenvalues are still very close in value and (2) the NNSD often contains values beyond the (0, 3) range, that is, there often exist eigenvalue spacings larger than 3.

**Comment by bentsherman** [comment]
@spficklin I think you were right. After going through these visualizations it's clear that there are a ton of gene pairs with very high correlation, which is exactly what we saw with our original GTEX GEM. Setting the `--minexpr` parameter to 0 during similarity is likely the solution here, but I'll have to check. We should also probably document this issue since I think it will be relevant for any GEM with more than 10K genes.

**Comment by bentsherman** [comment]
Added to the documentation.

The expression threshold helped but I'm not sure if it's a fool-proof solution. I think there might be other issues involved with large and diverse GEMs like panGTEX / panTCGA, and right now the best approach (if the expression threshold isn't enough, which was the case for panGTEX) I think is to examine the scatter plots with `visualize.py` or use EdgeScaping!
